import "dotenv/config"
import { PrismaClient } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter } as never)

const AFFILIATE_URL = "https://phiogen.is/?ref=PEPS"

function phiogenUrl(slug: string): string {
  return `https://phiogen.is/products/${slug}?ref=PEPS`
}

function phiogenImg(slug: string): string {
  return `https://phiogen.is/images/products/${slug}.png`
}

function isBundle(name: string): boolean {
  return name.includes("Blend") || name.includes("Stack") || name.includes("GLOW") || name.includes("KLOW") || name.includes("Cagri-")
}

const FEATURED_NAMES = new Set([
  "BPC-157 10mg",
  "TB-500 (Thymosin Beta-4) 10mg",
  "Ipamorelin 10mg",
  "CJC-1295 No DAC 5mg",
  "Semaglutide 3mg",
  "Tirzepatide 15mg",
  "Epitalon 10mg",
  "GHK-Cu 50mg",
  "Selank 10mg",
  "BPC-157 + TB-500 Blend 10mg",
])

type RawProduct = {
  name: string
  slug: string
  description: string
  category: string
  price: number | null
  purity: string | null
}

const RAW_PRODUCTS: RawProduct[] = [
  // FAT LOSS / METABOLIC
  { name: "5-Amino-1MQ 5mg", slug: "5-amino-1mq-5mg", price: 19.99, purity: "98.9%", description: "Promotes fat loss by blocking NNMT enzyme to accelerate fat breakdown. Supports weight management by enhancing metabolism and boosting cellular energy. Preserves lean muscle mass and improves insulin sensitivity.", category: "All Peptides, Weight Loss" },
  { name: "5-Amino-1MQ 50mg", slug: "5-amino-1mq-50mg", price: 79.99, purity: "98.9%", description: "High-dose 5-Amino-1MQ for extended metabolic research. Blocks NNMT to promote fat breakdown, preserves lean muscle mass, improves insulin sensitivity, and boosts mitochondrial energy output.", category: "All Peptides, Weight Loss" },
  { name: "5-Amino-1MQ 50mg x60 Capsules", slug: "5-amino-1mq-capsules-50mg-x-60-capsules", price: 119.99, purity: "98.9%", description: "Oral capsule form of 5-Amino-1MQ for convenient metabolic research. Each capsule contains 50mg; 60-capsule supply. Enhances fat metabolism, preserves lean muscle, and boosts cellular NAD+ levels.", category: "All Peptides, Weight Loss" },
  { name: "AOD9604 2mg", slug: "aod9604-2mg", price: 39.99, purity: "99.0%", description: "Modified fragment of human growth hormone that targets abdominal fat reduction without IGF-1-related side effects. Stimulates lipolysis, inhibits lipogenesis, and supports cartilage and joint health.", category: "All Peptides, Weight Loss" },
  { name: "AOD9604 5mg", slug: "aod9604-5mg", price: 69.99, purity: "99.0%", description: "Mid-range AOD9604 vial for sustained fat loss research. Promotes lipolysis of adipose tissue, inhibits new fat formation, and offers documented joint and cartilage protective properties.", category: "All Peptides, Weight Loss" },
  { name: "AOD9604 10mg", slug: "aod9604-10mg", price: 119.99, purity: "99.0%", description: "High-dose AOD9604 for comprehensive fat metabolism research. Reduces abdominal fat, improves metabolic rate, and supports joint and cartilage health across extended study periods.", category: "All Peptides, Weight Loss" },
  { name: "L-Carnitine 400mg/mL", slug: "l-carnitine-400mg-ml", price: 39.99, purity: "99.5%", description: "Injectable L-Carnitine at 400mg/mL concentration. Transports long-chain fatty acids into mitochondria for beta-oxidation, enhances exercise performance, reduces muscle damage, and supports cardiovascular health.", category: "All Peptides, Weight Loss, Muscle Growth" },
  { name: "L-Carnitine 600mg/mL", slug: "l-carnitine-600mg-ml", price: 49.99, purity: "99.5%", description: "High-concentration injectable L-Carnitine at 600mg/mL. Maximizes fatty acid transport into mitochondria, improves energy metabolism, reduces fatigue, and supports lean body composition research.", category: "All Peptides, Weight Loss, Muscle Growth" },
  { name: "L-Carnitine 5-Pack 600mg", slug: "l-carnitine-5-pack-600mg", price: 89.99, purity: "99.5%", description: "Five-vial pack of L-Carnitine 600mg/mL for extended research. Supports sustained fatty acid oxidation, endurance enhancement, and lean mass preservation across multi-week protocols.", category: "All Peptides, Weight Loss, Muscle Growth" },
  { name: "SLU-PP-332 1mg x30 Capsules", slug: "slu-pp-332-1mg-x-30-capsules", price: 39.99, purity: "98.6%", description: "ERR-alpha/gamma agonist that mimics the metabolic effects of endurance exercise. Activates oxidative muscle fiber gene expression, enhances mitochondrial biogenesis, and promotes fat utilization.", category: "All Peptides, Weight Loss" },
  { name: "SLU-PP-332 1mg/mL 30mL", slug: "slu-pp-332-1mg-ml-30ml", price: 79.99, purity: "98.6%", description: "Injectable SLU-PP-332 ERR agonist. Activates the same metabolic pathways as endurance exercise, increasing fat oxidation and mitochondrial density in muscle tissue.", category: "All Peptides, Weight Loss" },
  { name: "SLU-PP-332 5mg/mL 30mL", slug: "slu-pp-332-5mg-ml-30ml", price: 99.99, purity: "98.6%", description: "High-concentration injectable SLU-PP-332 for advanced exercise-mimetic research. Drives ERR-alpha/gamma activation, oxidative fiber switching, and enhanced metabolic efficiency.", category: "All Peptides, Weight Loss" },
  { name: "SLU-PP-332 100mg x30 Capsules", slug: "slu-pp-332-100mg-x-30-capsules", price: 59.99, purity: "98.6%", description: "Oral SLU-PP-332 capsules at 100mg each. Activates ERR nuclear receptors to enhance fat oxidation, mitochondrial biogenesis, and aerobic capacity without physical exercise.", category: "All Peptides, Weight Loss" },
  { name: "SLU-PP-332 100mg x120 Capsules", slug: "slu-pp-332-100mg-x-120-capsules", price: 159.99, purity: "98.6%", description: "Extended-supply SLU-PP-332 capsules (100mg x120). Provides four months of ERR agonist research, supporting sustained fat oxidation, metabolic adaptation, and mitochondrial enhancement.", category: "All Peptides, Weight Loss" },
  { name: "Semaglutide 3mg", slug: "semaglutide-3mg", price: 49.99, purity: "99.1%", description: "GLP-1 receptor agonist that reduces appetite, slows gastric emptying, and promotes sustained weight loss. Improves insulin sensitivity and supports cardiovascular metabolic health.", category: "All Peptides, Weight Loss" },
  { name: "Semaglutide 6mg", slug: "semaglutide-6mg", price: 79.99, purity: "99.1%", description: "Mid-dose Semaglutide for multi-week GLP-1 research. Suppresses appetite through hypothalamic GLP-1 receptors, improves glycemic control, and supports progressive fat loss.", category: "All Peptides, Weight Loss" },
  { name: "Semaglutide 12mg", slug: "semaglutide-12mg", price: 129.99, purity: "99.0%", description: "High-dose Semaglutide for extended GLP-1 receptor agonist research. Provides sustained appetite suppression, blood sugar regulation, and significant fat mass reduction over longer study durations.", category: "All Peptides, Weight Loss" },
  { name: "Semaglutide 20mg", slug: "semaglutide-20mg", price: 189.99, purity: "99.0%", description: "Large-format Semaglutide vial for prolonged obesity and metabolic research. GLP-1 receptor agonism drives robust appetite reduction, improved insulin secretion, and progressive weight management.", category: "All Peptides, Weight Loss" },
  { name: "Semaglutide 30mg", slug: "semaglutide-30mg", price: 249.99, purity: "99.0%", description: "Bulk Semaglutide for comprehensive longitudinal GLP-1 studies. Supports sustained weight reduction, metabolic health improvement, and cardiovascular risk factor management.", category: "All Peptides, Weight Loss" },
  { name: "AICAR 50mg", slug: "aicar-50mg", price: 69.99, purity: "99.1%", description: "AMPK activator that mimics the metabolic effects of exercise. Enhances fat oxidation, improves cardiovascular endurance, promotes glucose uptake, and supports metabolic health without physical activity.", category: "All Peptides, Weight Loss, Muscle Growth" },
  { name: "BAM-15 30mg/mL 30mL", slug: "bam-15-30mg-ml-30ml", price: 89.99, purity: "98.5%", description: "Mitochondrial uncoupler that dissipates the proton gradient as heat to increase metabolic rate and fat oxidation. Promotes weight loss without reducing food intake or causing muscle wasting.", category: "All Peptides, Weight Loss" },
  { name: "BAM-15 50mg/mL 30mL", slug: "bam-15-50mg-ml-30ml", price: 129.99, purity: "98.5%", description: "High-concentration BAM-15 mitochondrial uncoupler. Accelerates fat oxidation by converting stored energy to heat, supporting obesity research with preserved lean mass and muscle function.", category: "All Peptides, Weight Loss" },
  { name: "Adipotide (FTPP) 5mg", slug: "adipotide-fttp-5mg", price: 89.99, purity: "98.7%", description: "Pro-apoptotic peptide that selectively targets blood vessels feeding white adipose tissue. Induces apoptosis of adipocyte-specific vasculature, leading to fat cell death and targeted fat mass reduction.", category: "All Peptides, Weight Loss" },
  { name: "Adipotide (FTPP) 10mg", slug: "adipotide-fttp-10mg", price: 149.99, purity: "98.7%", description: "High-dose Adipotide (FTPP) for advanced fat loss research. Selectively eliminates adipose vasculature, causing apoptosis of fat cells with documented reduction in abdominal and overall fat mass.", category: "All Peptides, Weight Loss" },
  { name: "Cagrilintide 5mg", slug: "cagrilintide-5mg", price: 99.99, purity: "98.8%", description: "Long-acting amylin analogue that reduces appetite, slows gastric emptying, and complements GLP-1-based weight loss protocols. Supports sustainable weight reduction and muscle mass preservation.", category: "All Peptides, Weight Loss" },
  { name: "Cagrilintide 10mg", slug: "cagrilintide-10mg", price: 169.99, purity: "98.8%", description: "High-dose Cagrilintide amylin analogue for extended appetite and weight research. Reduces caloric intake, improves glycemic control, and synergizes with GLP-1 agonists for additive fat loss.", category: "All Peptides, Weight Loss" },
  { name: "Mazdutide 6mg", slug: "mazdutide-6mg", price: 129.99, purity: "98.5%", description: "Dual GLP-1/glucagon receptor agonist promoting sustainable weight reduction through appetite suppression and enhanced energy expenditure. Preserves lean muscle during fat loss and improves metabolic efficiency.", category: "All Peptides, Weight Loss" },
  { name: "Survodutide 10mg", slug: "survodutide-10mg", price: 159.99, purity: "98.5%", description: "GLP-1/glucagon dual receptor agonist with potent metabolic effects. Reduces body weight through appetite suppression and increased energy expenditure, with additional hepatic fat reduction properties.", category: "All Peptides, Weight Loss" },
  { name: "O-304 (ATX-304) 100mg x60 Capsules", slug: "o-304-atx-304-100mg-x-60-capsules", price: 119.99, purity: "98.8%", description: "Pan-AMPK activator that mimics exercise-induced metabolic benefits. Improves insulin sensitivity, enhances fat oxidation, supports cardiovascular function, and reduces liver fat in metabolic research models.", category: "All Peptides, Weight Loss" },
  { name: "Tirzepatide 15mg", slug: "tirzepatide-15mg", price: 149.99, purity: "99.2%", description: "Dual GIP/GLP-1 receptor agonist delivering superior weight loss compared to single-agonist approaches. Controls appetite, improves insulin sensitivity, enhances metabolic health, and supports cardiovascular function.", category: "All Peptides, Weight Loss" },
  { name: "Tirzepatide 30mg", slug: "tirzepatide-30mg", price: 249.99, purity: "99.2%", description: "Mid-range Tirzepatide supply for extended dual incretin research. Potent GIP/GLP-1 co-agonism drives significant fat mass reduction, blood sugar control, and metabolic improvements.", category: "All Peptides, Weight Loss" },
  { name: "Tirzepatide 60mg", slug: "tirzepatide-60mg", price: 399.99, purity: "99.2%", description: "Bulk Tirzepatide for comprehensive longitudinal metabolic studies. Dual incretin co-agonism delivers the most clinically documented weight loss among incretin-based peptides.", category: "All Peptides, Weight Loss" },
  { name: "Retatrutide 10mg", slug: "retatrutide-10mg", price: 149.99, purity: "98.9%", description: "Triple GLP-1/GIP/glucagon receptor agonist for powerful metabolic research. Supports weight loss, preserves lean muscle, reduces food cravings, lowers blood pressure, and improves blood sugar control.", category: "All Peptides, Weight Loss" },
  { name: "Retatrutide 15mg", slug: "retatrutide-15mg", price: 199.99, purity: "98.9%", description: "Mid-dose triple agonist Retatrutide. Combines GLP-1, GIP, and glucagon receptor activation for synergistic appetite suppression, enhanced energy expenditure, and superior fat mass reduction.", category: "All Peptides, Weight Loss" },
  { name: "Retatrutide 20mg", slug: "retatrutide-20mg", price: 249.99, purity: "98.9%", description: "High-dose Retatrutide for extended triple incretin research. Delivers comprehensive metabolic optimization through simultaneous GLP-1, GIP, and glucagon receptor co-agonism.", category: "All Peptides, Weight Loss" },
  { name: "Retatrutide 30mg", slug: "retatrutide-30mg", price: 329.99, purity: "98.9%", description: "Bulk Retatrutide for longitudinal obesity research. Triple-receptor agonism provides the most comprehensive pharmacological weight loss mechanism available for research applications.", category: "All Peptides, Weight Loss" },
  { name: "Tesofensine 500mcg x30 Capsules", slug: "tesofensine-500mcg-x-30-capsules", price: 99.99, purity: "99.0%", description: "Triple monoamine reuptake inhibitor (serotonin, dopamine, noradrenaline) that reduces appetite through central nervous system mechanisms. Supports significant weight reduction and improved metabolic parameters.", category: "All Peptides, Weight Loss" },
  { name: "Tesofensine 500mcg x30 Tablets", slug: "tesofensine-500mcg-x-30-tablets", price: 99.99, purity: "99.0%", description: "Tablet form Tesofensine for CNS-mediated appetite suppression research. Inhibits reuptake of serotonin, dopamine, and noradrenaline to reduce caloric intake and support sustained weight loss.", category: "All Peptides, Weight Loss" },
  // GROWTH PEPTIDES
  { name: "GHRP-2 10mg", slug: "ghrp-2-10mg", price: 49.99, purity: "99.0%", description: "Ghrelin receptor agonist that triggers a strong growth hormone pulse. Enhances muscle growth, accelerates recovery, supports fat loss by boosting metabolism, and improves sleep quality.", category: "All Peptides, Muscle Growth" },
  { name: "GHRP-6 10mg", slug: "ghrp-6-10mg", price: 49.99, purity: "99.0%", description: "Potent ghrelin mimetic that stimulates GH release and appetite. Promotes muscle growth, accelerates tissue repair, supports fat metabolism, and improves immune function through elevated GH secretion.", category: "All Peptides, Muscle Growth" },
  { name: "CJC-1295 No DAC 5mg", slug: "cjc-1295-no-dac-5mg", price: 49.99, purity: "99.1%", description: "GHRH analogue producing a short, physiological GH pulse. Promotes lean muscle growth, accelerates recovery, boosts metabolism, and improves sleep quality with a natural pulsatile GH release pattern.", category: "All Peptides, Muscle Growth, Anti-Aging" },
  { name: "CJC-1295 No DAC 10mg", slug: "cjc-1295-no-dac-10mg", price: 79.99, purity: "99.1%", description: "High-dose CJC-1295 (no DAC) for extended GH secretagogue research. Stimulates physiological GH pulses to support lean muscle accrual, fat metabolism, and tissue repair.", category: "All Peptides, Muscle Growth, Anti-Aging" },
  { name: "CJC-1295 with DAC 10mg", slug: "cjc-1295-with-dac-10mg", price: 99.99, purity: "99.0%", description: "Long-acting GHRH analogue with Drug Affinity Complex extending half-life to 6-8 days via albumin binding. Provides sustained GH elevation, promoting lean muscle growth and anti-aging effects.", category: "All Peptides, Muscle Growth, Anti-Aging" },
  { name: "Gonadorelin Acetate", slug: "gonadorelin-acetate", price: 49.99, purity: "99.0%", description: "GnRH analogue that stimulates pituitary LH and FSH secretion. Supports testosterone production, maintains gonadal function, and is studied for HPG axis restoration and fertility research.", category: "All Peptides, Muscle Growth, Libido" },
  { name: "Ipamorelin 10mg", slug: "ipamorelin-10mg", price: 59.99, purity: "99.2%", description: "Highly selective ghrelin receptor agonist with minimal cortisol or prolactin elevation. Promotes lean muscle growth, enhances fat loss, accelerates tissue regeneration, and improves sleep quality.", category: "All Peptides, Muscle Growth, Anti-Aging" },
  { name: "Sermorelin 2mg", slug: "sermorelin-2mg", price: 39.99, purity: "99.0%", description: "29-amino acid GHRH analogue that stimulates natural GH release from the pituitary. Supports muscle growth, reduces body fat, increases energy, improves sleep quality, and has anti-aging properties.", category: "All Peptides, Muscle Growth, Anti-Aging" },
  { name: "Sermorelin 5mg", slug: "sermorelin-5mg", price: 69.99, purity: "99.0%", description: "Mid-dose Sermorelin for extended GH axis research. Stimulates pulsatile GH secretion, supporting lean muscle development, fat reduction, improved sleep architecture, and systemic anti-aging effects.", category: "All Peptides, Muscle Growth, Anti-Aging" },
  { name: "Sermorelin 10mg", slug: "sermorelin-10mg", price: 119.99, purity: "99.0%", description: "High-dose Sermorelin for prolonged GHRH research studies. Provides sustained pituitary GH stimulation for lean body composition improvement, metabolic enhancement, and longevity research.", category: "All Peptides, Muscle Growth, Anti-Aging" },
  { name: "Hexarelin 5mg", slug: "hexarelin-5mg", price: 59.99, purity: "99.0%", description: "Potent GHRP that produces one of the strongest GH pulses among secretagogues. Also has direct cardioprotective properties through GHS-R1a receptors in cardiac tissue. Enhances muscle growth and recovery.", category: "All Peptides, Muscle Growth" },
  { name: "Kisspeptin-10 5mg", slug: "kisspeptin-10-5mg", price: 59.99, purity: "98.9%", description: "Upstream HPG axis activator that stimulates GnRH release to drive LH and testosterone production. Enhances libido, supports fertility, and restores hormonal drive from the hypothalamic signaling level.", category: "All Peptides, Libido, Muscle Growth" },
  { name: "Kisspeptin-10 10mg", slug: "kisspeptin-10-10mg", price: 99.99, purity: "98.9%", description: "High-dose Kisspeptin-10 for extended HPG axis research. Activates GnRH neurons to restore gonadotropin pulsatility, testosterone secretion, fertility signaling, and sexual motivation.", category: "All Peptides, Libido, Muscle Growth" },
  { name: "PEG-MGF 2mg", slug: "peg-mgf-2mg", price: 69.99, purity: "98.8%", description: "PEGylated Mechano Growth Factor activates satellite cells for muscle repair and hypertrophy. Extended half-life via PEGylation allows systemic distribution, supporting muscle recovery and lean mass accrual.", category: "All Peptides, Muscle Growth" },
  { name: "IGF-1 LR3 1mg", slug: "igf-1-lr3-1mg", price: 79.99, purity: "98.7%", description: "Long-acting IGF-1 analogue that bypasses hepatic clearance to act directly on muscle tissue. Promotes satellite cell activation, myofibril hypertrophy, fat reduction, and enhanced cellular nutrient uptake.", category: "All Peptides, Muscle Growth" },
  { name: "Tesamorelin 10mg", slug: "tesamorelin-10mg", price: 119.99, purity: "99.1%", description: "GHRH analogue clinically proven to reduce visceral/abdominal fat. Enhances metabolic function, supports muscle maintenance, improves skin elasticity, and enhances mental clarity through GH axis activation.", category: "All Peptides, Muscle Growth, Weight Loss" },
  { name: "Tesamorelin 20mg", slug: "tesamorelin-20mg", price: 199.99, purity: "99.1%", description: "High-dose Tesamorelin for extended visceral fat and GH axis research. Provides sustained GHRH receptor activation for progressive abdominal fat reduction and metabolic improvement.", category: "All Peptides, Muscle Growth, Weight Loss" },
  // RECOVERY & HEALING
  { name: "Bacteriostatic Water 30mL", slug: "bacteriostatic-water-30ml", price: 12.99, purity: null, description: "Sterile water containing 0.9% benzyl alcohol for peptide reconstitution. Prevents bacterial growth after vial entry, extends multi-use shelf life, and maintains solution sterility across research sessions.", category: "Supplies" },
  { name: "Bacteriostatic Water USP 30mL", slug: "usp-bacteriostatic-water-30ml", price: 14.99, purity: null, description: "USP-grade bacteriostatic water for injection. Highest purity standard for peptide reconstitution, ensuring sterility, non-pyrogenicity, and reliable pH consistency across research protocols.", category: "Supplies" },
  { name: "BPC-157 10mg", slug: "bpc-157-10mg", price: 59.99, purity: "99.3%", description: "15-amino acid body protection compound with extensive tendon, muscle, gut, and nerve repair research. Upregulates GH receptors, promotes angiogenesis, reduces inflammation, and accelerates wound closure.", category: "All Peptides, Recovery & Repair, Muscle Growth" },
  { name: "BPC-157 Capsules 500mcg x60", slug: "bpc-157-capsules-500mcg-x-60-capsules", price: 79.99, purity: "99.0%", description: "Oral BPC-157 capsules for gastrointestinal and systemic research. Retains bioactivity when administered orally; studied for leaky gut, gastric protection, and systemic anti-inflammatory effects.", category: "All Peptides, Recovery & Repair" },
  { name: "TB-500 (Thymosin Beta-4) 10mg", slug: "tb-500-thymosin-beta-4-10mg", price: 59.99, purity: "99.0%", description: "Synthetic Thymosin Beta-4 promoting actin polymerization, cell migration, and AKT pathway activation for systemic tissue repair. Reduces inflammation, supports cardiac recovery, and improves flexibility.", category: "All Peptides, Recovery & Repair, Muscle Growth" },
  { name: "Thymulin 10mg", slug: "thymulin-10mg", price: 59.99, purity: "98.8%", description: "Thymic nonapeptide that promotes T-cell differentiation and maturation. Reduces pro-inflammatory cytokines IL-1 and IL-6, supports autoimmune regulation, and has documented anti-nociceptive properties.", category: "All Peptides, Immunity" },
  { name: "KPV 5mg", slug: "kpv-5mg", price: 59.99, purity: "99.0%", description: "Alpha-MSH-derived tripeptide with potent anti-inflammatory properties. Inhibits NF-kB signaling, reduces gut inflammation, supports wound healing, and modulates immune responses at mucosal surfaces.", category: "All Peptides, Recovery & Repair, Immunity" },
  { name: "KPV 10mg", slug: "kpv-10mg", price: 99.99, purity: "99.0%", description: "High-dose KPV for extended gut inflammation and immune modulation research. Effectively inhibits inflammatory cascades, promotes intestinal healing, and reduces systemic inflammatory burden.", category: "All Peptides, Recovery & Repair, Immunity" },
  { name: "Oxytocin 8mg", slug: "oxytocin-8mg", price: 69.99, purity: "99.0%", description: "Neuropeptide hormone with roles in social bonding, stress reduction, anti-inflammatory signaling, and wound healing. Studied for gut motility support, anxiety reduction, and tissue repair facilitation.", category: "All Peptides, Recovery & Repair, Brain/Nerve" },
  { name: "Oxytocin 10mg", slug: "oxytocin-10mg", price: 79.99, purity: "99.0%", description: "High-dose Oxytocin for comprehensive neuropeptide research. Supports prosocial behavior studies, stress hormone regulation, gut barrier function, and anti-inflammatory healing applications.", category: "All Peptides, Recovery & Repair, Brain/Nerve" },
  { name: "Thymosin Alpha-1 5mg", slug: "thymosin-alpha-1-5mg", price: 69.99, purity: "99.0%", description: "28-amino acid thymic peptide that activates T-helper 1 immunity, enhances antigen presentation, stimulates interferon production, and raises NK cell activity. Clinically used in 35+ countries.", category: "All Peptides, Immunity" },
  { name: "Thymosin Alpha-1 10mg", slug: "thymosin-alpha-1-10mg", price: 119.99, purity: "99.0%", description: "High-dose Thymosin Alpha-1 for extended immune optimization research. Restores T-cell function, enhances viral and bacterial immunity, and supports immune resilience in immunocompromised research models.", category: "All Peptides, Immunity" },
  { name: "Bronchogen 20mg", slug: "bronchogen-20mg", price: 79.99, purity: "98.8%", description: "Short peptide bioregulator targeting bronchial and lung tissue. Promotes bronchial epithelial cell restoration, reduces airway inflammation, and supports pulmonary function and respiratory health.", category: "All Peptides, Recovery & Repair, Immunity" },
  { name: "Cardiogen 20mg", slug: "cardiogen-20mg", price: 79.99, purity: "98.8%", description: "Peptide bioregulator specific to cardiac tissue. Supports cardiomyocyte function, promotes cardiac protein synthesis, reduces oxidative damage to heart tissue, and supports cardiovascular resilience.", category: "All Peptides, Recovery & Repair" },
  { name: "Cartalax 20mg", slug: "cartalax-20mg", price: 79.99, purity: "98.8%", description: "Connective tissue peptide bioregulator supporting cartilage and bone regeneration. Promotes chondrocyte and osteoblast activity, reduces joint degeneration, and supports musculoskeletal structural integrity.", category: "All Peptides, Recovery & Repair, Skin/Tissue/Bone" },
  { name: "Chonluten 20mg", slug: "chonluten-20mg", price: 79.99, purity: "98.8%", description: "Peptide bioregulator that targets bronchial and mucosal tissues. Supports epithelial cell regeneration, improves mucosal barrier integrity, and promotes respiratory tissue recovery.", category: "All Peptides, Recovery & Repair" },
  { name: "Cortagen 20mg", slug: "cortagen-20mg", price: 79.99, purity: "98.8%", description: "Neuropeptide bioregulator supporting cerebral cortex and central nervous system function. Promotes neuronal recovery, supports cognitive resilience, and reduces age-related neurological decline.", category: "All Peptides, Recovery & Repair, Brain/Nerve" },
  { name: "Crystagen 20mg", slug: "crystagen-20mg", price: 79.99, purity: "98.8%", description: "Connective tissue bioregulator promoting collagen synthesis and structural tissue integrity. Supports skin firmness, joint cartilage health, and connective tissue remodeling.", category: "All Peptides, Recovery & Repair, Skin/Tissue/Bone" },
  { name: "Livagen 20mg", slug: "livagen-20mg", price: 79.99, purity: "98.8%", description: "Hepatic peptide bioregulator that supports liver cell function and regeneration. Promotes hepatoprotective activity, reduces liver inflammation, and supports detoxification pathway integrity.", category: "All Peptides, Recovery & Repair" },
  { name: "Ovagen 20mg", slug: "ovagen-20mg", price: 79.99, purity: "98.8%", description: "Peptide bioregulator targeting gastrointestinal and hepatic tissue. Supports liver and gut tissue regeneration, reduces oxidative damage, and improves organ-specific protein synthesis.", category: "All Peptides, Recovery & Repair" },
  { name: "Pancragen 20mg", slug: "pancragen-20mg", price: 79.99, purity: "98.8%", description: "Pancreatic peptide bioregulator supporting exocrine and endocrine pancreatic function. Promotes beta-cell health, supports insulin regulation, and reduces pancreatic oxidative stress.", category: "All Peptides, Recovery & Repair" },
  { name: "Prostamax 20mg", slug: "prostamax-20mg", price: 79.99, purity: "98.8%", description: "Prostate-specific peptide bioregulator supporting prostate gland health and function. Reduces prostate inflammation, promotes healthy tissue turnover, and supports urogenital function.", category: "All Peptides, Recovery & Repair" },
  { name: "Thymogen 20mg", slug: "thymogen-20mg", price: 79.99, purity: "98.8%", description: "Dipeptide thymic factor that stimulates T-lymphocyte production and immune maturation. Supports immune system restoration, improves infection resistance, and reduces immunosenescence.", category: "All Peptides, Immunity" },
  { name: "Vesilute 20mg", slug: "vesilute-20mg", price: 79.99, purity: "98.8%", description: "Peptide bioregulator targeting bladder and urinary tract tissue. Supports urothelial cell restoration, reduces urinary tract inflammation, and promotes healthy bladder function.", category: "All Peptides, Recovery & Repair" },
  { name: "Vesugen 20mg", slug: "vesugen-20mg", price: 79.99, purity: "98.8%", description: "Vascular peptide bioregulator that promotes endothelial cell health and blood vessel integrity. Supports angiogenesis, reduces vascular oxidative stress, and improves circulation.", category: "All Peptides, Recovery & Repair" },
  { name: "Vilon 20mg", slug: "vilon-20mg", price: 79.99, purity: "98.8%", description: "Dipeptide bioregulator with immunomodulatory and anti-aging properties. Stimulates thymic activity, restores immune function, and supports longevity signaling through epigenetic mechanisms.", category: "All Peptides, Recovery & Repair, Anti-Aging" },
  { name: "Testagen 20mg", slug: "testagen-20mg", price: 89.99, purity: "98.8%", description: "Peptide bioregulator targeting testicular and male reproductive tissue. Supports testosterone production, promotes Leydig cell function, and maintains male reproductive health.", category: "All Peptides, Recovery & Repair, Muscle Growth" },
  { name: "ARA-290 10mg", slug: "ara-290-10mg", price: 89.99, purity: "98.7%", description: "Non-hematopoietic EPO analogue that activates the innate repair receptor to reduce chronic inflammation and neuropathic pain without erythropoietic effects. Supports tissue protection and metabolic health.", category: "All Peptides, Recovery & Repair" },
  { name: "SS-31 10mg", slug: "ss-31-10mg", price: 99.99, purity: "98.9%", description: "Mitochondria-targeted antioxidant peptide that concentrates at the inner mitochondrial membrane. Reduces oxidative stress, restores ATP production, and protects against ischemia-reperfusion injury.", category: "All Peptides, Anti-Aging, Recovery & Repair" },
  { name: "SS-31 25mg", slug: "ss-31-25mg", price: 189.99, purity: "98.9%", description: "Mid-dose SS-31 for extended mitochondrial protection research. Maintains cardiolipin function, reduces mitochondrial ROS, improves bioenergetics, and protects cardiac and renal tissue from oxidative damage.", category: "All Peptides, Anti-Aging, Recovery & Repair" },
  { name: "SS-31 50mg", slug: "ss-31-50mg", price: 329.99, purity: "98.9%", description: "Bulk SS-31 for comprehensive mitochondrial health studies. Provides sustained mitochondria-targeted antioxidant protection, supports energy metabolism restoration, and reduces oxidative pathology.", category: "All Peptides, Anti-Aging, Recovery & Repair" },
  { name: "LL-37 10mg", slug: "ll-37-10mg", price: 99.99, purity: "98.9%", description: "Human cathelicidin antimicrobial peptide with broad-spectrum bactericidal activity and wound healing properties. Disrupts bacterial membranes, neutralizes LPS, promotes angiogenesis, and modulates immune responses.", category: "All Peptides, Immunity, Skin/Tissue/Bone" },
  { name: "MOTS-c 10mg", slug: "mots-c-10mg", price: 129.99, purity: "98.8%", description: "Mitochondria-derived peptide that activates AMPK and restores metabolic homeostasis. Enhances insulin sensitivity, promotes glucose metabolism, reduces inflammation, and slows aging processes.", category: "All Peptides, Anti-Aging, Weight Loss" },
  { name: "MOTS-c 20mg", slug: "mots-c-20mg", price: 219.99, purity: "98.8%", description: "High-dose MOTS-c for extended mitochondrial and metabolic research. Restores youthful insulin sensitivity, activates AMPK-driven fat oxidation, and reduces systemic inflammation.", category: "All Peptides, Anti-Aging, Weight Loss" },
  { name: "MOTS-c 40mg", slug: "mots-c-40mg", price: 379.99, purity: "98.8%", description: "Bulk MOTS-c for longitudinal mitochondrial signaling and longevity studies. Provides comprehensive AMPK and metabolic pathway activation for aging, obesity, and insulin resistance research.", category: "All Peptides, Anti-Aging, Weight Loss" },
  { name: "VIP 5mg", slug: "vip-5mg", price: 79.99, purity: "98.8%", description: "Vasoactive Intestinal Peptide with potent anti-inflammatory, immunomodulatory, and neuroprotective properties. Reduces cytokine storms, supports gut motility, and promotes pulmonary and neurological health.", category: "All Peptides, Recovery & Repair, Immunity" },
  { name: "VIP 10mg", slug: "vip-10mg", price: 139.99, purity: "98.8%", description: "High-dose Vasoactive Intestinal Peptide for advanced immune and neurological research. Suppresses inflammatory cytokines, regulates gut function, and provides neuroprotective effects across multiple tissue types.", category: "All Peptides, Recovery & Repair, Immunity" },
  // ANTI-AGING & LONGEVITY
  { name: "Epitalon 10mg", slug: "epitalon-10mg", price: 59.99, purity: "99.2%", description: "Tetrapeptide that activates telomerase to extend telomere length, providing anti-aging benefits. Improves sleep quality, strengthens immune function, and has documented antioxidant and potential cancer-preventive properties.", category: "All Peptides, Anti-Aging" },
  { name: "Epitalon 50mg", slug: "epitalon-50mg", price: 139.99, purity: "99.4%", description: "High-dose Epitalon for extended telomerase activation research. Supports telomere restoration, immune rejuvenation, circadian rhythm normalization, and longevity signaling across prolonged study periods.", category: "All Peptides, Anti-Aging" },
  { name: "NA-Epitalon 10mg", slug: "na-epitalon-10mg", price: 79.99, purity: "99.0%", description: "N-acetylated Epitalon variant with potentially enhanced bioavailability. Activates telomerase, supports telomere integrity, and provides anti-aging benefits through improved peptide stability.", category: "All Peptides, Anti-Aging" },
  { name: "GHK-Cu 50mg", slug: "ghk-cu-50mg", price: 50.00, purity: "99.1%", description: "Copper-binding tripeptide that modulates over 4,000 genes involved in skin, hair, and tissue regeneration. Boosts collagen synthesis, stimulates wound healing, reduces inflammation, and protects against oxidative damage.", category: "All Peptides, Skin/Tissue/Bone, Anti-Aging" },
  { name: "GHK-Cu 100mg", slug: "ghk-cu-100mg", price: 89.99, purity: "99.1%", description: "High-dose GHK-Cu for comprehensive skin biology and anti-aging research. Upregulates collagen I/III/IV, elastin, and glycosaminoglycans; activates hair follicle renewal and nerve growth factor expression.", category: "All Peptides, Skin/Tissue/Bone, Anti-Aging" },
  { name: "Glutathione 200mg", slug: "glutathione-200mg", price: 49.99, purity: "99.3%", description: "Master endogenous antioxidant that neutralizes free radicals, supports detoxification, and maintains cellular redox balance. Reduces oxidative stress, supports immune function, and has skin-brightening properties.", category: "All Peptides, Anti-Aging" },
  { name: "Glutathione 600mg", slug: "glutathione-600mg", price: 89.99, purity: "99.3%", description: "Mid-dose Glutathione for sustained antioxidant and detoxification research. Replenishes cellular GSH stores, supports hepatic Phase II detoxification, and reduces systemic oxidative burden.", category: "All Peptides, Anti-Aging" },
  { name: "Glutathione 1500mg", slug: "glutathione-1500mg", price: 179.99, purity: "99.3%", description: "High-dose Glutathione for comprehensive oxidative stress and longevity research. Restores cellular antioxidant capacity, supports mitochondrial health, and provides broad systemic protective effects.", category: "All Peptides, Anti-Aging" },
  { name: "NAD+ 500mg", slug: "nad-500mg", price: 79.99, purity: "99.5%", description: "Nicotinamide adenine dinucleotide coenzyme critical for energy metabolism and cellular repair. Supports mitochondrial function, activates sirtuins, promotes DNA repair, and combats age-related NAD+ decline.", category: "All Peptides, Anti-Aging" },
  { name: "NAD+ 1000mg", slug: "nad-1000mg", price: 139.99, purity: "99.5%", description: "High-dose NAD+ for extended longevity and metabolic research. Restores sirtuin activity, enhances mitochondrial biogenesis, supports neurological health, and counters the progressive NAD+ decline of aging.", category: "All Peptides, Anti-Aging" },
  { name: "Methylene Blue 10mg/mL 50mL", slug: "methylene-blue-10mg-ml-50ml", price: 59.99, purity: "99.5%", description: "Mitochondrial electron carrier that enhances cellular respiration and ATP production. Studied for cognitive enhancement, neuroprotection, anti-aging effects, and antimicrobial properties.", category: "All Peptides, Anti-Aging, Brain/Nerve" },
  { name: "Melanotan I 10mg", slug: "melanotan-1-10mg", price: 59.99, purity: "99.0%", description: "Linear alpha-MSH analogue that selectively activates MC1R for UV-independent skin tanning. Provides photoprotection by stimulating melanin production without the broader melanocortin receptor effects of MT-II.", category: "All Peptides, Libido, Skin/Tissue/Bone" },
  { name: "Melanotan II 10mg", slug: "melanotan-2-10mg", price: 59.99, purity: "99.0%", description: "Cyclic melanocortin peptide activating MC1R through MC5R. Produces UV-independent tanning, enhances libido through MC4R activation, reduces appetite, and has documented erectile function effects.", category: "All Peptides, Libido, Skin/Tissue/Bone" },
  { name: "PT-141 10mg", slug: "pt-141-10mg", price: 69.99, purity: "99.0%", description: "FDA-approved (Vyleesi) melanocortin peptide acting centrally on MC3R/MC4R to enhance libido and sexual motivation. Addresses sexual dysfunction through brain pathways rather than peripheral blood flow mechanisms.", category: "All Peptides, Libido" },
  { name: "SNAP-8 10mg", slug: "snap-8-10mg", price: 45.00, purity: "98.9%", description: "Octapeptide analogue of SNAP-25 that reduces muscle contraction-induced facial wrinkles by inhibiting catecholamine release at neuromuscular junctions. Studied as a topical anti-wrinkle agent.", category: "All Peptides, Anti-Aging, Skin/Tissue/Bone" },
  { name: "P21 10mg", slug: "p21-10mg", price: 89.99, purity: "98.7%", description: "CNTF-derived nootropic peptide with neurogenic and BDNF-stimulating properties. Promotes neurogenesis, enhances memory consolidation, and supports cognitive resilience through STAT3 and BDNF pathway activation.", category: "All Peptides, Brain/Nerve, Anti-Aging" },
  { name: "RU-58841 50mg x30mL", slug: "ru-58841-50mg-x-30ml", price: 79.99, purity: "98.8%", description: "Topical androgen receptor antagonist studied for androgenetic alopecia. Blocks DHT binding at the hair follicle level without systemic anti-androgenic effects, supporting hair retention research.", category: "All Peptides, Skin/Tissue/Bone" },
  { name: "RU-58841 50mg x60mL", slug: "ru-58841-50mg-x-60ml", price: 129.99, purity: "98.8%", description: "Extended-supply topical RU-58841 for prolonged hair loss research. Provides two-month supply of topical androgen receptor blockade for androgenetic alopecia studies.", category: "All Peptides, Skin/Tissue/Bone" },
  { name: "PNC-27 30mg", slug: "pnc-27-30mg", price: 119.99, purity: "98.6%", description: "p53-derived peptide that selectively targets cancer cell membranes, inducing membranolysis in tumor cells overexpressing HDM-2. Studied for anti-cancer properties without toxicity to normal cells.", category: "All Peptides, Anti-Aging" },
  { name: "Abaloparatide 3mg", slug: "abaloparatide-3mg", price: 149.99, purity: "98.7%", description: "PTHrP analogue with FDA approval for osteoporosis. Promotes osteoblast-driven bone formation with preferential anabolic activity, improving bone mineral density and reducing fracture risk.", category: "All Peptides, Anti-Aging, Skin/Tissue/Bone" },
  { name: "FOXO4-DRI 10mg", slug: "fox04-dri-10mg", price: 149.99, purity: "98.7%", description: "Senolytic peptide that disrupts FOXO4-p53 interaction in senescent cells, triggering apoptosis of dysfunctional cells while sparing healthy tissue. Studied for cellular rejuvenation and age-related dysfunction.", category: "All Peptides, Anti-Aging" },
  { name: "ACE-031 1mg", slug: "ace-031-1mg", price: 199.99, purity: "98.5%", description: "Recombinant fusion protein inhibiting myostatin and activin to remove the biological brake on skeletal muscle growth. Produces significant lean mass increases independent of GH signaling in preclinical studies.", category: "All Peptides, Muscle Growth" },
  // COGNITIVE & NOOTROPIC
  { name: "DSIP 5mg", slug: "dsip-delta-sleep-inducing-peptide-5mg", price: 49.99, purity: "99.0%", description: "Delta sleep-inducing peptide that promotes deep, restorative sleep by modulating delta-wave brain activity. Regulates cortisol levels, normalizes circadian rhythms, and has neuroprotective and antioxidant properties.", category: "All Peptides, Brain/Nerve" },
  { name: "DSIP 10mg", slug: "dsip-delta-sleep-inducing-peptide-10mg", price: 79.99, purity: "99.0%", description: "Mid-dose DSIP for extended sleep architecture research. Enhances delta-wave sleep, reduces sleep-onset latency, normalizes cortisol, and supports neuroprotection through sustained delta wave modulation.", category: "All Peptides, Brain/Nerve" },
  { name: "DSIP 15mg", slug: "dsip-delta-sleep-inducing-peptide-15mg", price: 99.99, purity: "99.0%", description: "High-dose DSIP for longitudinal sleep and stress hormone research. Provides sustained delta sleep promotion, circadian regulation, and stress hormone normalization across extended study periods.", category: "All Peptides, Brain/Nerve" },
  { name: "Selank 10mg", slug: "selank-10mg", price: 69.99, purity: "99.0%", description: "Anxiolytic heptapeptide derived from tuftsin with GABA-A modulation, BDNF upregulation, and anti-anxiety effects. Reduces anxiety, enhances cognitive function, stabilizes mood, and improves sleep without sedation.", category: "All Peptides, Brain/Nerve" },
  { name: "NA-Selank Amidate 10mg", slug: "na-selank-amidate-10mg", price: 79.99, purity: "99.0%", description: "N-acetylated, C-amidated Selank with enhanced bioavailability and stability. Provides improved anxiolytic and cognitive-enhancing effects versus standard Selank through increased peptide resistance to enzymatic degradation.", category: "All Peptides, Brain/Nerve" },
  { name: "NA-Selank Amidate 30mg", slug: "na-selank-amidate-30mg", price: 179.99, purity: "99.0%", description: "High-dose NA-Selank Amidate for extended anxiolytic and cognitive research. Superior stability formulation provides sustained GABA modulation, BDNF elevation, and immune support across long protocols.", category: "All Peptides, Brain/Nerve" },
  { name: "Pinealon 10mg", slug: "pinealon-10mg", price: 69.99, purity: "98.8%", description: "Tripeptide pineal gland bioregulator with neuroprotective and anti-aging brain effects. Promotes neuronal regeneration, supports melatonin regulation, improves cognitive resilience, and reduces cerebral oxidative stress.", category: "All Peptides, Brain/Nerve, Anti-Aging" },
  { name: "Pinealon 20mg", slug: "pinealon-20mg", price: 119.99, purity: "98.8%", description: "High-dose Pinealon for extended pineal gland and neuroprotection research. Supports circadian regulation, reduces neuronal oxidative damage, and promotes cognitive longevity through pineal bioregulation.", category: "All Peptides, Brain/Nerve, Anti-Aging" },
  { name: "PE-22-28 10mg", slug: "pe-22-28-10mg", price: 79.99, purity: "98.8%", description: "BDNF loop domain peptide mimetic that activates TrkB receptors to produce rapid antidepressant effects. Promotes neuroplasticity, supports synaptic remodeling, and enhances mood regulation.", category: "All Peptides, Brain/Nerve" },
  { name: "Adamax 10mg", slug: "adamax-10mg", price: 99.99, purity: "98.7%", description: "BDNF-mimetic cognitive enhancer that activates TrkB signaling without the side effects of full-length BDNF. Promotes neuroprotection, synaptic plasticity, memory consolidation, and neurogenesis.", category: "All Peptides, Brain/Nerve" },
  { name: "N-Acetyl Semax Amidate 30mg", slug: "n-acetyl-semax-amidate-30mg", price: 149.99, purity: "99.0%", description: "Most potent Semax variant with N-acetylation and C-amidation for maximum bioavailability. Drives BDNF production, enhances dopaminergic signaling, sharpens focus and memory, and provides neuroprotection.", category: "All Peptides, Brain/Nerve" },
  // BLENDS & STACKS
  { name: "BPC-157 + TB-500 Blend 10mg", slug: "bpc-157-tb-500-blend-bpc-157-5mg-tb-500-5mg", price: 59.99, purity: "99.0%", description: "Premier tissue repair stack combining BPC-157 5mg + TB-500 5mg. Complementary mechanisms: BPC-157 drives local angiogenesis and GH receptor upregulation while TB-500 promotes systemic cell migration and actin polymerization.", category: "Peptides Cycles, Peptides Bundles, Recovery & Repair" },
  { name: "BPC-157 + TB-500 Blend 20mg", slug: "bpc-157-tb-500-blend-bpc-157-10mg-tb-500-10mg", price: 99.99, purity: "99.0%", description: "High-dose BPC-157 10mg + TB-500 10mg synergistic recovery blend. Double-strength repair stack for comprehensive musculoskeletal healing, addressing inflammation resolution, proliferation, and tissue remodeling.", category: "Peptides Cycles, Peptides Bundles, Recovery & Repair" },
  { name: "Ipamorelin/CJC-1295 Blend 10mg", slug: "ipamorelin-cjc-1295-blend-cjc-1295-5mg-ipa-5mg", price: 89.99, purity: "99.0%", description: "Classic GH stack: CJC-1295 5mg (GHRH) + Ipamorelin 5mg (ghrelin mimetic). Synergistic dual-pathway GH release — 4-6x more effective than either alone. Promotes lean muscle growth, fat loss, and recovery.", category: "Peptides Cycles, Peptides Bundles, Muscle Growth" },
  { name: "Ipamorelin/CJC-1295 Blend 10mg v2", slug: "ipamorelin-cjc-1295-blend-cjc-1295-5mg-ipamorelin-5mg", price: 89.99, purity: "99.0%", description: "Alternate batch CJC-1295 5mg + Ipamorelin 5mg growth hormone stack. Stimulates complementary GH pathways for superior lean mass, fat metabolism, recovery acceleration, and sleep quality improvement.", category: "Peptides Cycles, Peptides Bundles, Muscle Growth" },
  { name: "Ipamorelin/Tesamorelin Blend 13mg", slug: "ipamorelin-tesamorelin-blend-ipa-3mg-tesa-10mg", price: 129.99, purity: "99.0%", description: "Ipamorelin 3mg + Tesamorelin 10mg blend targeting visceral fat reduction and lean mass. Tesamorelin reduces abdominal fat while Ipamorelin drives muscle-sparing GH pulses for optimized body composition.", category: "Peptides Cycles, Peptides Bundles, Muscle Growth, Weight Loss" },
  { name: "Ipamorelin/Tesamorelin Blend 15mg", slug: "ipamorelin-tesamorelin-blend-ipa-5mg-tesa-10mg", price: 149.99, purity: "99.0%", description: "Higher-dose Ipamorelin 5mg + Tesamorelin 10mg blend for comprehensive GH and visceral fat research. Combines anabolic GH pulse stimulation with proven abdominal fat-reducing GHRH activity.", category: "Peptides Cycles, Peptides Bundles, Muscle Growth, Weight Loss" },
  { name: "IPA/TESA Blend 15mg", slug: "ipa-tesa-blend-ipa-5mg-tesa-10mg-15mg", price: 149.99, purity: "99.0%", description: "Ipamorelin 5mg + Tesamorelin 10mg body composition stack. Drives simultaneous lean muscle growth through GH pulsation and visceral fat reduction through GHRH receptor activation.", category: "Peptides Cycles, Peptides Bundles, Muscle Growth, Weight Loss" },
  { name: "GLOW Blend 50mg", slug: "glow-blend-50mg", price: 89.99, purity: "98.8%", description: "Skin and tissue regeneration blend combining collagen-stimulating peptides. Boosts collagen synthesis, supports skin regeneration, enhances hair thickness, and strengthens connective tissue for a comprehensive glow protocol.", category: "Peptides Cycles, Peptides Bundles, Skin/Tissue/Bone, Anti-Aging" },
  { name: "GLOW Blend 70mg", slug: "glow-blend-70mg", price: 109.99, purity: "98.8%", description: "Enhanced GLOW formula at 70mg total for advanced skin and tissue research. Amplifies collagen and elastin production, promotes hair follicle renewal, and supports deep connective tissue remodeling.", category: "Peptides Cycles, Peptides Bundles, Skin/Tissue/Bone, Anti-Aging" },
  { name: "KLOW Blend 80mg", slug: "klow-blend-80mg", price: 119.99, purity: "98.8%", description: "Premium 80mg skin and longevity synergy blend. Combines regenerative peptides for comprehensive skin health, collagen restoration, hair rejuvenation, and cellular anti-aging across a structured research cycle.", category: "Peptides Cycles, Peptides Bundles, Skin/Tissue/Bone, Anti-Aging" },
  { name: "Cagri-Reta 5mg", slug: "cagri-reta-5mg", price: 129.99, purity: "98.5%", description: "Cagrilintide + Retatrutide synergy blend for powerful weight loss research. Combines amylin analogue appetite suppression with triple GLP-1/GIP/glucagon agonism for additive fat reduction.", category: "Peptides Cycles, Peptides Bundles, Weight Loss" },
  { name: "Cagri-Reta 10mg", slug: "cagri-reta-10mg", price: 189.99, purity: "98.5%", description: "High-dose Cagrilintide + Retatrutide blend for extended metabolic obesity research. Multi-pathway appetite and energy regulation: amylin + triple incretin agonism for superior fat mass reduction.", category: "Peptides Cycles, Peptides Bundles, Weight Loss" },
  { name: "Cagri-Sema Blend 10mg", slug: "cagri-sema-blend-5mg-cagrilintide-5mg-sema-10mg", price: 179.99, purity: "98.7%", description: "Cagrilintide 5mg + Semaglutide blend combining amylin and GLP-1 receptor agonism. Complementary appetite suppression mechanisms produce additive weight loss, improved glycemic control, and metabolic benefits.", category: "Peptides Cycles, Peptides Bundles, Weight Loss" },
  { name: "Reta-Cagri 5mg/5mg", slug: "reta-cagri-5mg-5mg", price: 149.99, purity: "98.5%", description: "Retatrutide 5mg + Cagrilintide 5mg balanced dual-compound stack. Pairs the triple incretin agonist Retatrutide with Cagrilintide amylin receptor activation for synergistic fat loss and appetite regulation.", category: "Peptides Cycles, Peptides Bundles, Weight Loss" },
]

const CATEGORIES_DATA = [
  { name: "Muscle Growth", slug: "muscle-growth", icon: "TrendingUp", color: "#2563eb", description: "Peptides that promote lean muscle growth, enhance recovery, and support GH secretion.", heroDescription: "Research peptides for muscle growth and body composition optimization.", seoDescription: "Buy muscle growth peptides — Ipamorelin, CJC-1295, Sermorelin, GHRP-2, IGF-1 LR3, Tesamorelin from Phiogen.", sortOrder: 0 },
  { name: "Recovery & Repair", slug: "recovery-repair", icon: "Zap", color: "#16a34a", description: "Peptides that accelerate tissue healing, reduce inflammation, and speed recovery.", heroDescription: "The most studied tissue repair peptides for injury recovery and healing.", seoDescription: "Buy recovery peptides — BPC-157 10mg, TB-500 10mg, BPC-157+TB-500 Blend, KPV, ARA-290 from Phiogen.", sortOrder: 1 },
  { name: "Anti-Aging", slug: "anti-aging", icon: "Clock", color: "#9333ea", description: "Peptides that combat cellular aging, activate telomerase, and promote longevity.", heroDescription: "Research peptides targeting the fundamental hallmarks of aging.", seoDescription: "Buy anti-aging peptides — Epitalon, GHK-Cu, NAD+, FOXO4-DRI, SS-31, Glutathione from Phiogen.", sortOrder: 2 },
  { name: "Weight Loss", slug: "weight-loss", icon: "Flame", color: "#ea580c", description: "Peptides that support fat metabolism, reduce appetite, and improve body composition.", heroDescription: "Research peptides for weight management and metabolic health.", seoDescription: "Buy weight loss peptides — Semaglutide, Tirzepatide, Retatrutide, AOD9604, 5-Amino-1MQ from Phiogen.", sortOrder: 3 },
  { name: "Brain/Nerve", slug: "brain-nerve", icon: "Brain", color: "#0891b2", description: "Nootropic peptides that enhance cognition, memory, and neuroprotection.", heroDescription: "Research peptides for cognitive enhancement and neuroprotection.", seoDescription: "Buy nootropic peptides — N-Acetyl Semax Amidate, NA-Selank Amidate, DSIP, Pinealon, PE-22-28 from Phiogen.", sortOrder: 4 },
  { name: "Immunity", slug: "immunity", icon: "Shield", color: "#15803d", description: "Peptides that strengthen immune function, reduce inflammation, and fight infection.", heroDescription: "Immune-boosting research peptides for enhanced immune function.", seoDescription: "Buy immune peptides — Thymosin Alpha-1, Thymulin, LL-37, KPV, VIP, Thymogen from Phiogen.", sortOrder: 5 },
  { name: "Libido", slug: "libido", icon: "Heart", color: "#e11d48", description: "Peptides that support sexual health, enhance libido, and improve reproductive function.", heroDescription: "Research peptides for sexual health and libido enhancement.", seoDescription: "Buy libido peptides — PT-141, Kisspeptin-10, Melanotan I & II, Gonadorelin from Phiogen.", sortOrder: 6 },
  { name: "Skin/Tissue/Bone", slug: "skin-tissue-bone", icon: "Star", color: "#d97706", description: "Peptides for skin regeneration, collagen synthesis, hair growth, and bone health.", heroDescription: "Research peptides for skin, tissue, and bone regeneration.", seoDescription: "Buy skin peptides — GHK-Cu, BPC-157, SNAP-8, RU-58841, Abaloparatide, GLOW Blend from Phiogen.", sortOrder: 7 },
  { name: "Peptides Cycles", slug: "peptides-cycles", icon: "Package", color: "#7c3aed", description: "Pre-built synergistic peptide blends and stacks for comprehensive results.", heroDescription: "Complete peptide blends and stacks for focused research goals.", seoDescription: "Buy peptide blends — BPC-157+TB-500 Blend, Ipamorelin/CJC-1295, GLOW Blend, Cagri-Reta, Cagri-Sema from Phiogen.", sortOrder: 8 },
  { name: "Supplies", slug: "supplies", icon: "Package2", color: "#6b7280", description: "Reconstitution supplies: bacteriostatic water for peptide research.", heroDescription: "Essential supplies for peptide reconstitution and research.", seoDescription: "Bacteriostatic water for peptide reconstitution — standard and USP-grade from Phiogen.", sortOrder: 9 },
]

async function main() {
  console.log("Clearing old data...")

  // Delete all old products and categories first
  await prisma.product.deleteMany({})
  await prisma.category.deleteMany({})
  console.log("Old data cleared.")

  // Seed categories
  for (const cat of CATEGORIES_DATA) {
    await prisma.category.create({
      data: {
        ...cat,
        stats: [],
        content: `## About ${cat.name} Peptides\n\nExplore our selection of ${cat.name.toLowerCase()} research peptides from Phiogen. All products are for research use only.\n\n## Research Applications\n\nThese peptides have been studied in various research contexts related to ${cat.name.toLowerCase()}.`,
        faq: [
          { question: `What are ${cat.name} peptides?`, answer: `${cat.name} peptides are research compounds studied for their effects on ${cat.name.toLowerCase()}-related pathways.` },
          { question: "Are these peptides safe?", answer: "All products are for research use only. Not for human consumption. Consult a qualified physician before any use." },
        ],
      },
    })
  }
  console.log(`Seeded ${CATEGORIES_DATA.length} categories`)

  // Seed products
  for (let i = 0; i < RAW_PRODUCTS.length; i++) {
    const p = RAW_PRODUCTS[i]
    const cats = p.category.split(",").map((c: string) => c.trim()).filter((c: string) => c !== "All Peptides" && c !== "Peptides Bundles")
    const descParts = p.description.split(".")
    const shortDescription = descParts[0] ? descParts[0].trim() + "." : p.description.slice(0, 120)

    await prisma.product.create({
      data: {
        name: p.name,
        slug: p.slug,
        imageUrl: phiogenImg(p.slug),
        productUrl: phiogenUrl(p.slug),
        price: p.price,
        priceFormatted: p.price ? `$${p.price.toFixed(2)}` : null,
        description: p.description,
        shortDescription,
        categories: cats,
        isFeatured: FEATURED_NAMES.has(p.name),
        badge: p.purity ? `${p.purity} Pure` : null,
        isBundle: isBundle(p.name),
        isInStock: true,
        sortOrder: i,
      },
    })
  }
  console.log(`Seeded ${RAW_PRODUCTS.length} products`)
  console.log("Database seeded with Phiogen data successfully!")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
